CREATE SEQUENCE IF NOT EXISTS token_id_seq START WITH 1 INCREMENT BY 1;

CREATE TABLE comment
(
    comment_id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    content           VARCHAR(255)                            NOT NULL,
    created_at        TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    user_id           UUID                                    NOT NULL,
    user_post_id      UUID                                    NOT NULL,
    parent_comment_id BIGINT,
    CONSTRAINT pk_comment PRIMARY KEY (comment_id)
);

CREATE TABLE donations
(
    donation_id    UUID                        NOT NULL,
    amount         DECIMAL                     NOT NULL,
    transaction_id VARCHAR(255),
    created_at     TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    is_anonymous   BOOLEAN                     NOT NULL,
    user_id        UUID,
    fundraising_id UUID                        NOT NULL,
    CONSTRAINT pk_donations PRIMARY KEY (donation_id)
);

CREATE TABLE email_confirmation_tokens
(
    id           UUID                        NOT NULL,
    token        VARCHAR(255)                NOT NULL,
    created_at   TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    expires_at   TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    confirmed_at TIMESTAMP WITHOUT TIME ZONE,
    user_id      UUID                        NOT NULL,
    CONSTRAINT pk_email_confirmation_tokens PRIMARY KEY (id)
);

CREATE TABLE fundraising
(
    fundraising_id UUID                        NOT NULL,
    title          VARCHAR(255)                NOT NULL,
    description    VARCHAR(5238)               NOT NULL,
    goal_amount    DECIMAL                     NOT NULL,
    start_date     TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    end_date       TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    created_at     TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    status         VARCHAR(255)                NOT NULL,
    user_id        UUID                        NOT NULL,
    category_id    BIGINT,
    CONSTRAINT pk_fundraising PRIMARY KEY (fundraising_id)
);

CREATE TABLE fundraising_category
(
    category_id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    category_name VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_fundraising_category PRIMARY KEY (category_id)
);

CREATE TABLE intellectual_property
(
    ip_id       UUID                        NOT NULL,
    name        VARCHAR(255)                NOT NULL,
    description VARCHAR(5238),
    type_ip     VARCHAR(255)                NOT NULL,
    created_at  TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    file_ip     VARCHAR(255),
    status      VARCHAR(255)                NOT NULL,
    user_id     UUID,
    category_id BIGINT,
    CONSTRAINT pk_intellectual_property PRIMARY KEY (ip_id)
);

CREATE TABLE intellectual_property_category
(
    category_id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    category_name VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_intellectual_property_category PRIMARY KEY (category_id)
);

CREATE TABLE payout_requests
(
    payout_id      UUID                        NOT NULL,
    amount         DECIMAL                     NOT NULL,
    card_number    VARCHAR(255)                NOT NULL,
    created_at     TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    status         VARCHAR(255)                NOT NULL,
    fundraising_id UUID                        NOT NULL,
    CONSTRAINT pk_payout_requests PRIMARY KEY (payout_id)
);

CREATE TABLE permission_requests
(
    id                   UUID                        NOT NULL,
    user_id              UUID                        NOT NULL,
    requested_permission VARCHAR(255)                NOT NULL,
    status               VARCHAR(255)                NOT NULL,
    message              TEXT,
    created_at           TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT pk_permission_requests PRIMARY KEY (id)
);

CREATE TABLE tokens
(
    id            BIGINT       NOT NULL,
    token         VARCHAR(255) NOT NULL,
    refresh_token VARCHAR(255) NOT NULL,
    token_type    VARCHAR(255) NOT NULL,
    expired       BOOLEAN      NOT NULL,
    revoked       BOOLEAN      NOT NULL,
    user_id       UUID,
    CONSTRAINT pk_tokens PRIMARY KEY (id)
);

CREATE TABLE user_permissions
(
    user_id    UUID NOT NULL,
    permission VARCHAR(255)
);

CREATE TABLE user_post
(
    user_post_id     UUID                        NOT NULL,
    post_header      VARCHAR(300)                NOT NULL,
    post_description VARCHAR(255),
    post_text        TEXT,
    created_at       TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    photo            VARCHAR(255),
    user_id          UUID                        NOT NULL,
    post_topic_id    BIGINT,
    CONSTRAINT pk_user_post PRIMARY KEY (user_post_id)
);

CREATE TABLE user_post_tag
(
    post_topic_id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    post_topic_name VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_user_post_tag PRIMARY KEY (post_topic_id)
);

CREATE TABLE user_profiles
(
    user_profile_id    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    website            VARCHAR(255),
    location           VARCHAR(255),
    bio                VARCHAR(255),
    areas_of_expertise VARCHAR(255),
    user_id            UUID                                    NOT NULL,
    CONSTRAINT pk_user_profiles PRIMARY KEY (user_profile_id)
);

CREATE TABLE users
(
    user_id        UUID         NOT NULL,
    username       VARCHAR(255) NOT NULL,
    email          VARCHAR(255) NOT NULL,
    password       VARCHAR(255) NOT NULL,
    full_name      VARCHAR(255),
    user_role      VARCHAR(255),
    created_at     TIMESTAMP WITHOUT TIME ZONE,
    email_verified BOOLEAN      NOT NULL,
    CONSTRAINT pk_users PRIMARY KEY (user_id)
);

ALTER TABLE email_confirmation_tokens
    ADD CONSTRAINT uc_email_confirmation_tokens_token UNIQUE (token);

ALTER TABLE user_profiles
    ADD CONSTRAINT uc_user_profiles_user UNIQUE (user_id);

ALTER TABLE comment
    ADD CONSTRAINT FK_COMMENT_ON_PARENT_COMMENT FOREIGN KEY (parent_comment_id) REFERENCES comment (comment_id);

ALTER TABLE comment
    ADD CONSTRAINT FK_COMMENT_ON_USER FOREIGN KEY (user_id) REFERENCES users (user_id);

ALTER TABLE comment
    ADD CONSTRAINT FK_COMMENT_ON_USER_POST FOREIGN KEY (user_post_id) REFERENCES user_post (user_post_id);

ALTER TABLE donations
    ADD CONSTRAINT FK_DONATIONS_ON_FUNDRAISING FOREIGN KEY (fundraising_id) REFERENCES fundraising (fundraising_id);

ALTER TABLE donations
    ADD CONSTRAINT FK_DONATIONS_ON_USER FOREIGN KEY (user_id) REFERENCES users (user_id);

ALTER TABLE email_confirmation_tokens
    ADD CONSTRAINT FK_EMAIL_CONFIRMATION_TOKENS_ON_USER FOREIGN KEY (user_id) REFERENCES users (user_id);

ALTER TABLE fundraising
    ADD CONSTRAINT FK_FUNDRAISING_ON_CATEGORY FOREIGN KEY (category_id) REFERENCES fundraising_category (category_id);

ALTER TABLE fundraising
    ADD CONSTRAINT FK_FUNDRAISING_ON_USER FOREIGN KEY (user_id) REFERENCES users (user_id);

ALTER TABLE intellectual_property
    ADD CONSTRAINT FK_INTELLECTUAL_PROPERTY_ON_CATEGORY FOREIGN KEY (category_id) REFERENCES intellectual_property_category (category_id);

ALTER TABLE intellectual_property
    ADD CONSTRAINT FK_INTELLECTUAL_PROPERTY_ON_USER FOREIGN KEY (user_id) REFERENCES users (user_id);

ALTER TABLE payout_requests
    ADD CONSTRAINT FK_PAYOUT_REQUESTS_ON_FUNDRAISING FOREIGN KEY (fundraising_id) REFERENCES fundraising (fundraising_id);

ALTER TABLE permission_requests
    ADD CONSTRAINT FK_PERMISSION_REQUESTS_ON_USER FOREIGN KEY (user_id) REFERENCES users (user_id);

ALTER TABLE tokens
    ADD CONSTRAINT FK_TOKENS_ON_USER FOREIGN KEY (user_id) REFERENCES users (user_id);

ALTER TABLE user_post
    ADD CONSTRAINT FK_USER_POST_ON_POST_TOPIC FOREIGN KEY (post_topic_id) REFERENCES user_post_tag (post_topic_id);

ALTER TABLE user_post
    ADD CONSTRAINT FK_USER_POST_ON_USER FOREIGN KEY (user_id) REFERENCES users (user_id);

ALTER TABLE user_profiles
    ADD CONSTRAINT FK_USER_PROFILES_ON_USER FOREIGN KEY (user_id) REFERENCES users (user_id);

ALTER TABLE user_permissions
    ADD CONSTRAINT fk_user_permissions_on_user FOREIGN KEY (user_id) REFERENCES users (user_id);