CREATE SEQUENCE IF NOT EXISTS token_id_seq START WITH 1 INCREMENT BY 1;

CREATE TABLE comment
(
    comment_id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    content      VARCHAR(255)                            NOT NULL,
    created_at   TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    user_id      UUID                                    NOT NULL,
    user_post_id UUID                                    NOT NULL,
    CONSTRAINT pk_comment PRIMARY KEY (comment_id)
);

CREATE TABLE donations
(
    donation_id    UUID    NOT NULL,
    amount         DECIMAL NOT NULL,
    transaction_id VARCHAR(255),
    created_at     TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    is_anonymous   BOOLEAN NOT NULL,
    user_id        UUID    NOT NULL,
    fundraising_id UUID    NOT NULL,
    CONSTRAINT pk_donations PRIMARY KEY (donation_id)
);

CREATE TABLE fundraising
(
    fundraising_id UUID         NOT NULL,
    title          VARCHAR(255) NOT NULL,
    description    VARCHAR(255) NOT NULL,
    goal_amount    DECIMAL      NOT NULL,
    start_date     TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    end_date       TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    created_at     TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    status         VARCHAR(255) NOT NULL,
    user_id        UUID         NOT NULL,
    category_id    BIGINT,
    CONSTRAINT pk_fundraising PRIMARY KEY (fundraising_id)
);

CREATE TABLE fundraising_category
(
    category_id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    category_name VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_fundraising_category PRIMARY KEY (category_id)
);

CREATE TABLE intellectual_property
(
    ip_id       UUID         NOT NULL,
    name        VARCHAR(255) NOT NULL,
    description VARCHAR(255),
    type_ip     VARCHAR(255) NOT NULL,
    created_at  TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    file_ip     VARCHAR(255),
    status      VARCHAR(255) NOT NULL,
    user_id     UUID,
    category_id BIGINT,
    CONSTRAINT pk_intellectual_property PRIMARY KEY (ip_id)
);

CREATE TABLE intellectual_property_category
(
    category_id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    category_name VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_intellectual_property_category PRIMARY KEY (category_id)
);

CREATE TABLE photo
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name            VARCHAR(255),
    type            VARCHAR(255),
    photo_file_path VARCHAR(255),
    CONSTRAINT pk_photo PRIMARY KEY (id)
);

CREATE TABLE post_tag_topic
(
    post_topic_id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    post_topic_name VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_post_tag_topic PRIMARY KEY (post_topic_id)
);

CREATE TABLE tag
(
    tag_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name   VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_tag PRIMARY KEY (tag_id)
);

CREATE TABLE tokens
(
    id            BIGINT       NOT NULL,
    token         VARCHAR(255) NOT NULL,
    refresh_token VARCHAR(255) NOT NULL,
    token_type    VARCHAR(255) NOT NULL,
    expired       BOOLEAN      NOT NULL,
    revoked       BOOLEAN      NOT NULL,
    user_id       UUID,
    CONSTRAINT pk_tokens PRIMARY KEY (id)
);

CREATE TABLE user_permissions
(
    user_id    UUID NOT NULL,
    permission VARCHAR(255)
);

CREATE TABLE user_post
(
    user_post_id     UUID         NOT NULL,
    post_header      VARCHAR(300) NOT NULL,
    post_description VARCHAR(255),
    post_text        VARCHAR(255),
    created_at       TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    photo            VARCHAR(255),
    user_id          UUID         NOT NULL,
    post_topic_id    BIGINT,
    CONSTRAINT pk_user_post PRIMARY KEY (user_post_id)
);

CREATE TABLE user_post_like
(
    like_id      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at   TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    user_id      UUID                                    NOT NULL,
    user_post_id UUID                                    NOT NULL,
    CONSTRAINT pk_user_post_like PRIMARY KEY (like_id)
);

CREATE TABLE user_profile_tags
(
    tag_id          BIGINT NOT NULL,
    user_profile_id BIGINT NOT NULL,
    CONSTRAINT pk_user_profile_tags PRIMARY KEY (tag_id, user_profile_id)
);

CREATE TABLE user_profiles
(
    user_profile_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    website         VARCHAR(255),
    location        VARCHAR(255),
    user_id         UUID                                    NOT NULL,
    CONSTRAINT pk_user_profiles PRIMARY KEY (user_profile_id)
);

CREATE TABLE user_settings
(
    user_id               UUID    NOT NULL,
    email_notifications   BOOLEAN NOT NULL,
    marketing_opt_in      BOOLEAN NOT NULL,
    language              VARCHAR(50),
    timezone              VARCHAR(50),
    theme                 VARCHAR(50),
    accessibility_options TEXT,
    CONSTRAINT pk_user_settings PRIMARY KEY (user_id)
);

CREATE TABLE user_t
(
    user_id         UUID         NOT NULL,
    username        VARCHAR(255) NOT NULL,
    email           VARCHAR(255) NOT NULL,
    password        VARCHAR(255) NOT NULL,
    full_name       VARCHAR(255),
    user_role       VARCHAR(255),
    created_at      TIMESTAMP WITHOUT TIME ZONE,
    profile_picture VARCHAR(255),
    bio             VARCHAR(255),
    CONSTRAINT pk_user_t PRIMARY KEY (user_id)
);

ALTER TABLE user_post_like
    ADD CONSTRAINT uc_d918f92f373be54882f74ba02 UNIQUE (user_id, user_post_id);

ALTER TABLE tag
    ADD CONSTRAINT uc_tag_name UNIQUE (name);

ALTER TABLE user_profiles
    ADD CONSTRAINT uc_user_profiles_user UNIQUE (user_id);

ALTER TABLE comment
    ADD CONSTRAINT FK_COMMENT_ON_USER FOREIGN KEY (user_id) REFERENCES user_t (user_id);

ALTER TABLE comment
    ADD CONSTRAINT FK_COMMENT_ON_USER_POST FOREIGN KEY (user_post_id) REFERENCES user_post (user_post_id);

ALTER TABLE donations
    ADD CONSTRAINT FK_DONATIONS_ON_FUNDRAISING FOREIGN KEY (fundraising_id) REFERENCES fundraising (fundraising_id);

ALTER TABLE donations
    ADD CONSTRAINT FK_DONATIONS_ON_USER FOREIGN KEY (user_id) REFERENCES user_t (user_id);

ALTER TABLE fundraising
    ADD CONSTRAINT FK_FUNDRAISING_ON_CATEGORY FOREIGN KEY (category_id) REFERENCES fundraising_category (category_id);

ALTER TABLE fundraising
    ADD CONSTRAINT FK_FUNDRAISING_ON_USER FOREIGN KEY (user_id) REFERENCES user_t (user_id);

ALTER TABLE intellectual_property
    ADD CONSTRAINT FK_INTELLECTUAL_PROPERTY_ON_CATEGORY FOREIGN KEY (category_id) REFERENCES intellectual_property_category (category_id);

ALTER TABLE intellectual_property
    ADD CONSTRAINT FK_INTELLECTUAL_PROPERTY_ON_USER FOREIGN KEY (user_id) REFERENCES user_t (user_id);

ALTER TABLE tokens
    ADD CONSTRAINT FK_TOKENS_ON_USER FOREIGN KEY (user_id) REFERENCES user_t (user_id);

ALTER TABLE user_post_like
    ADD CONSTRAINT FK_USER_POST_LIKE_ON_USER FOREIGN KEY (user_id) REFERENCES user_t (user_id);

ALTER TABLE user_post_like
    ADD CONSTRAINT FK_USER_POST_LIKE_ON_USER_POST FOREIGN KEY (user_post_id) REFERENCES user_post (user_post_id);

ALTER TABLE user_post
    ADD CONSTRAINT FK_USER_POST_ON_POST_TOPIC FOREIGN KEY (post_topic_id) REFERENCES post_tag_topic (post_topic_id);

ALTER TABLE user_post
    ADD CONSTRAINT FK_USER_POST_ON_USER FOREIGN KEY (user_id) REFERENCES user_t (user_id);

ALTER TABLE user_profiles
    ADD CONSTRAINT FK_USER_PROFILES_ON_USER FOREIGN KEY (user_id) REFERENCES user_t (user_id);

ALTER TABLE user_settings
    ADD CONSTRAINT FK_USER_SETTINGS_ON_USER FOREIGN KEY (user_id) REFERENCES user_t (user_id);

ALTER TABLE user_profile_tags
    ADD CONSTRAINT fk_useprotag_on_tag FOREIGN KEY (tag_id) REFERENCES tag (tag_id);

ALTER TABLE user_profile_tags
    ADD CONSTRAINT fk_useprotag_on_user_profiles FOREIGN KEY (user_profile_id) REFERENCES user_profiles (user_profile_id);

ALTER TABLE user_permissions
    ADD CONSTRAINT fk_user_permissions_on_user FOREIGN KEY (user_id) REFERENCES user_t (user_id);